@FirstWebApi_HostAddress = https://localhost:7144

GET {{FirstWebApi_HostAddress}}/
Accept: application/json

###

GET http://comax.co.il
Accept: application/json

###
POST {{FirstWebApi_HostAddress}}/api/products

{
  "id":"101"
}

###
GET {{FirstWebApi_HostAddress}}/api/products
###
POST {{FirstWebApi_HostAddress}}/api/payment/cancel
// var controller = new PayementConroller
//controller.CancelPayment({})
{
  "paymentCode" : "PAY001"
}
###
POST {{FirstWebApi_HostAddress}}/api/payment 
// var controller = new PayementConroller
// controller.DoPayment({})

Content-Type: application/json

{
  "id": 123,
  "paymentCode": "PAY001",
  "amount":987
}

###

GET {{FirstWebApi_HostAddress}}/api/payment/status

###
OPTIONS {{FirstWebApi_HostAddress}}/api
