@FirstWebApi_HostAddress = https://localhost:7144

GET {{FirstWebApi_HostAddress}}/
Accept: application/json

###

GET http://comax.co.il
Accept: application/json

###
POST {{FirstWebApi_HostAddress}}/api/products

{
  "id":"101"
}

###
GET {{FirstWebApi_HostAddress}}/api/products
###

POST {{FirstWebApi_HostAddress}}/api/payment
Content-Type: application/json

{
  "id": 123,
  "paymentCode": "PAY001",
  "amount":-9
}

###

GET {{FirstWebApi_HostAddress}}/api/payment/status

###
OPTIONS {{FirstWebApi_HostAddress}}/api
