@FirstWebApi_HostAddress = https://localhost:7144


//https://source.dot.net/#Microsoft.AspNetCore/WebApplicationBuilder.cs,99aa99b238241808

###
GET {{FirstWebApi_HostAddress}}/api/config
###

###
GET {{FirstWebApi_HostAddress}}/api/config/getPath
###


###
GET {{FirstWebApi_HostAddress}}/api/config/complex
###


###
GET {{FirstWebApi_HostAddress}}/api/config/complexSnapshot
###

GET {{FirstWebApi_HostAddress}}/
Accept: application/json

###

GET http://comax.co.il
Accept: application/json

###
POST {{FirstWebApi_HostAddress}}/api/products

{
  "id":"101"
}

###
GET {{FirstWebApi_HostAddress}}/api/products
###
POST {{FirstWebApi_HostAddress}}/api/payment/cancel
// var controller = new PayementConroller
//controller.CancelPayment({})
{
  "paymentCode" : "PAY001"
}
###
POST {{FirstWebApi_HostAddress}}/api/payment 
// var controller = new PayementConroller
// controller.DoPayment({})

Content-Type: application/json

{
  "id": 123,
  "paymentCode": "PAY001",
  "amount":987
}

###

GET {{FirstWebApi_HostAddress}}/api/payment/status

###
OPTIONS {{FirstWebApi_HostAddress}}/api
